import { Gantt, } from 'rc-gantt'
import { DefaultRecordType, } from 'rc-gantt/dist/types/types'


export const data: Gantt.Record<DefaultRecordType>[] = [ {
  id: '1',
  name: 'Проектные работы',
  startDate: new Date(2023, 8, 15),
  endDate: new Date(2026, 1, 4),
  collapsed: false,
  disabled: true,
  group: true,
  children: [ {
    id: '2',
    name: 'Подписание Договора',
    startDate: new Date(2023, 8, 15),
    endDate: new Date(2023, 8, 15),
    collapsed: false,
    disabled: true,
  }, {
    id: '3',
    name: 'Выполнение работ (оказание услуг) по разработке Проектной документации (в т.ч. Инженерные изыскания) по объекту',
    startDate: new Date(2023, 8, 15),
    endDate: new Date(2026, 12, 15),
    collapsed: false,
    disabled: true,
    group: true,
    children: [ {
      id: '4',
      name: 'Разработка предпроектной документации',
      startDate: new Date(2023, 8, 15),
      endDate: new Date(2024, 12, 13),
      collapsed: false,
      disabled: true,
      group: true,
      children: [
        {
          id: '5',
          name: 'Предварительная посадка корпусов и задание на ИГЭ',
          startDate: new Date(2023, 8, 15),
          endDate: new Date(2024, 8, 23),
          collapsed: false,
          disabled: true,
        },
        {
          id: '6',
          name: 'Сит план М 1:2000',
          startDate: new Date(2023, 10, 10),
          endDate: new Date(2023, 10, 19),
          collapsed: false,
          disabled: true,
        },
        {
          id: '7',
          name: 'Топографический план (Геоподоснова М 1:500)',
          startDate: new Date(2023, 8, 15),
          endDate: new Date(2023, 10, 9),
          collapsed: false,
          disabled: true,
        },
        {
          id: '8',
          name: 'ТЭПы и сбор нагрузок',
          startDate: new Date(2024, 3, 25),
          endDate: new Date(2024, 5, 24),
          collapsed: false,
          disabled: true,
        },
        {
          id: '9',
          name: 'Предпроектная стадия разработана',
          startDate: new Date(2024, 8, 26),
          endDate: new Date(2024, 8, 26),
          collapsed: false,
          disabled: true,
        },
      ],
    }, {
      id: '10',
      name: 'Получение ТУ на вынос инженерных сетей',
      startDate: new Date(2023, 8, 15),
      endDate: new Date(2024, 9, 2),
      collapsed: false,
      disabled: true,
      group: true,
      children: [
        {
          id: '11',
          name: 'Газификация',
          startDate: new Date(2023, 12, 5),
          endDate: new Date(2024, 9, 2),
          collapsed: false,
          disabled: true,
        },
        {
          id: '12',
          name: 'Сети связи',
          startDate: new Date(2023, 9, 12),
          endDate: new Date(2024, 2, 14),
          collapsed: false,
          disabled: true,
        },
        {
          id: '13',
          name: 'Электроосвещение',
          startDate: new Date(2023, 10, 19),
          endDate: new Date(2023, 12, 6),
          collapsed: false,
          disabled: true,
        },
        {
          id: '14',
          name: 'Водоотведение',
          startDate: new Date(2023, 10, 20),
          endDate: new Date(2023, 23, 23),
          collapsed: false,
          disabled: true,
        },
        {
          id: '15',
          name: 'Теплоснабжение',
          startDate: new Date(2023, 8, 15),
          endDate: new Date(2023, 8, 15),
          collapsed: false,
          disabled: true,
        },
        {
          id: '16',
          name: 'Водоснабжение',
          startDate: new Date(2024, 1, 25),
          endDate: new Date(2024, 4, 17),
          collapsed: false,
          disabled: true,
        },
        {
          id: '17',
          name: 'Канализация',
          startDate: new Date(2024, 1, 25),
          endDate: new Date(2024, 4, 15),
          collapsed: false,
          disabled: true,
        },
        {
          id: '18',
          name: 'Электроснабжение',
          startDate: new Date(2023, 10, 19),
          endDate: new Date(2024, 1, 3),
          collapsed: false,
          disabled: true,
        },
        {
          id: '19',
          name: 'ТУ на вынос инженерных сетей получены',
          startDate: new Date(2024, 9, 2),
          endDate: new Date(2024, 9, 2),
          collapsed: false,
          disabled: true,
        },
      ],
    }, ],
  }, ],
}, ]
